# Copyright 2000-2021 Nokia
#
# Licensed under the Apache License 2.0
# SPDX-License-Identifier: Apache-2.0
#

sudo: false

language: java

jdk:
  - oraclejdk8

install: ./gradlew --version

script: ./gradlew --continue
