#!/bin/bash
 
rpm -qa | grep -qw buildah || yum install -y buildah

# change storage driver to vfs to avoid overlay issue (on CentOS)
[ ! -f /etc/fedora-release ] && sed -i 's/driver = "overlay"/driver = "vfs"/' /etc/containers/storage.conf

set -o errexit
set -x

buildah pull csf-docker-delivered.repo.lab.pl.alcatel-lucent.com/java_base/11/nano:CENTOS_JAVA11
casr=$(buildah from --format=docker csf-docker-delivered.repo.lab.pl.alcatel-lucent.com/java_base/11/nano:CENTOS_JAVA11)
mnt_casr=$(buildah mount $casr)

buildah config --label MAINTAINER="Nokia CASR Team" "${casr}"
buildah config --label IMAGE_NAME="casr-base-11" "${casr}"
buildah config --label BASE_IMAGE="csf-docker-delivered.repo.lab.pl.alcatel-lucent.com/java_base/11/nano:CENTOS_JAVA11" "${casr}"

buildah run "${casr}" -- mkdir /casr
buildah run "${casr}" -- mkdir /home/casr
buildah copy "${casr}" 'create_runtime.sh' '/casr/'
buildah copy "${casr}" 'create_jvm.sh' '/casr/'
buildah copy "${casr}" 'create_casr.sh' '/casr/'
buildah copy "${casr}" 'launch.sh' '/casr/'
buildah copy "${casr}" 'healthcheck.sh' '/casr/'
buildah copy "${casr}" 'jdeps.sh' '/tmp/'
buildah run "${casr}" -- chmod -R 774 /casr

yum install -y --installroot $mnt_casr \
               --exclude=kernel* --setopt=tsflags=nodocs \
               --setopt=override_install_langs=en_US.utf8 \
    unzip wget

buildah copy "${casr}" 'jvm.opt' '/tmp/'

buildah commit $casr casr-base-11:latest
buildah unmount $casr
buildah rm $casr

buildah push localhost/casr-base-11:latest docker-archive:tmp-tar.tgz:casr-base-11:latest
docker load -i tmp-tar.tgz
rm -f tmp-tar.tgz