# Copyright 2000-2021 Nokia
#
# Licensed under the Apache License 2.0
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "nokia.com/v1beta1"
kind: CasrFunction
metadata:
  name: kafka-write
spec:
  function:
      location: file:///tmp/com.nokia.as.jaxrs.jersey.sless.stest.unit-1.0.0.jar
  exec:
      ttl: 50000
