# Copyright 2000-2021 Nokia
#
# Licensed under the Apache License 2.0
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "nokia.com/v1beta1"
kind: CasrRoute
metadata:
    name: routeHTTPunsecure
spec:
  function:
    name: kafka-write
  route:
    path: /unsecure
    type: http

