#!/bin/bash
 
rpm -qa | grep -qw buildah || yum install -y buildah

# change storage driver to vfs to avoid overlay issue (on CentOS)
[ ! -f /etc/fedora-release ] && sed -i 's/driver = "overlay"/driver = "vfs"/' /etc/containers/storage.conf

set -o errexit
set -x

buildah pull csf-docker-delivered.repo.lab.pl.alcatel-lucent.com/java_base/8/nano:CENTOS_JAVA8
casr=$(buildah from --format=docker csf-docker-delivered.repo.lab.pl.alcatel-lucent.com/java_base/8/nano:CENTOS_JAVA8)
mnt_casr=$(buildah mount $casr)

buildah config --label MAINTAINER="Nokia CASR Team" "${casr}"
buildah config --label IMAGE_NAME="casr-base" "${casr}"
buildah config --label BASE_IMAGE="csf-docker-delivered.repo.lab.pl.alcatel-lucent.com/java_base/8/nano:CENTOS_JAVA8" "${casr}"

buildah run "${casr}" -- mkdir /casr
buildah run "${casr}" -- mkdir /home/casr
buildah copy "${casr}" 'create_runtime.sh' '/casr/'

yum install -y --installroot $mnt_casr \
               --exclude=kernel* --setopt=tsflags=nodocs \
               --setopt=override_install_langs=en_US.utf8 \
    hostname shadow-utils telnet unzip which wget

buildah run "${casr}" -- groupadd --gid 7777 -r casr
buildah run "${casr}" -- useradd --no-log-init -r --gid 7777 --uid 7777 casr
buildah run "${casr}" -- chown -R 7777:7777 /casr
buildah run "${casr}" -- chown -R 7777:7777 /home/casr
buildah run "${casr}" -- chmod -R 740 /casr

buildah config --user 7777 "${casr}"
buildah config --port 17000 "${casr}"

buildah copy --chown casr:casr "${casr}" 'jvm.opt' '/tmp/'
buildah config --entrypoint '["sh", "-c", "./start.sh -l $CASR_LOGGER"]' "${casr}"

buildah commit $casr casr-base:latest
buildah unmount $casr
buildah rm $casr

buildah push localhost/casr-base:latest docker-archive:tmp-tar.tgz:casr-base:latest
docker load -i tmp-tar.tgz
rm -f tmp-tar.tgz