apiVersion: v1
kind: Pod
metadata:
  name: http
  labels:
spec:
  containers:
  - name: httpioh
    image: image
    ports:
    - name: mux-h-test
      protocol: TCP
      containerPort: 8080
status:
  containerStatuses:
  - containerID: abcde12345
    name: httpioh
    ready: false
    restartCount: 0
    image: image
    imageID: abcde12345
  podIP: 172.1.2.3
