apiVersion: v1
kind: Pod
metadata:
  name: meters
  labels:
spec:
  containers:
  - name: metersioh
    image: image
    ports:
    - name: mux-m-meters
      protocol: TCP
      containerPort: 8080
status:
  containerStatuses:
  - containerID: wcxds77862
    name: metersioh
    ready: false
    restartCount: 0
    image: image
    imageID: wcxds77862
  podIP: 172.1.3.5
