# Copyright 2000-2021 Nokia
#
# Licensed under the Apache License 2.0
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: v1
kind: Pod
metadata:
  labels:
    com.nokia.casr.loadbalancer: test
  name: permanent
spec:
  containers:
  - name: permanent
    image: image
    ports:
    - name: permanent-tcp
      protocol: TCP
      containerPort: 8080
status:
  containerStatuses:
  - containerID: abcde12345
    name: permanent
    ready: true
    restartCount: 0
    image: image
    imageID: abcde12345
  podIP: 172.1.2.3