# Copyright 2000-2021 Nokia
#
# Licensed under the Apache License 2.0
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: v1
kind: Pod
metadata:
  labels:
    label1: value1
    label2: value2
  name: volatile
spec:
  containers:
  - name: volatile
    image: image
    ports:
    - name: volatile-tcp
      protocol: TCP
      containerPort: 8080
    - name: volatile-udp
      protocol: UDP
      containerPort: 10000
status:
  containerStatuses:
  - containerID: 12345abcde
    name: volatile
    ready: false
    image: image
    imageID: 12345abcde
  podIP: 172.4.5.6
