/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper */

#ifndef _Included_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
#define _Included_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_RTOINFO
 * Signature: (II)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_rtoinfo;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1RTOINFO
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_RTOINFO
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_rtoinfo;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1RTOINFO
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_ASSOCINFO
 * Signature: (II)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_assocparams;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1ASSOCINFO
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_ASSOCINFO
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_assocparams;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1ASSOCINFO
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_INITMSG
 * Signature: (I)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_initmsg;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1INITMSG
  (JNIEnv *, jobject, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_INITMSG
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_initmsg;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1INITMSG
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_ADAPTATION_LAYER
 * Signature: (I)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_setadaptation;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1ADAPTATION_1LAYER
  (JNIEnv *, jobject, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_ADAPTATION_LAYER
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_setadaptation;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1ADAPTATION_1LAYER
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_PEER_ADDR_PARAMS
 * Signature: (II)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_paddrparams;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1PEER_1ADDR_1PARAMS
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_PEER_ADDR_PARAMS
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_paddrparams;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1PEER_1ADDR_1PARAMS
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_DEFAULT_SEND_PARAM
 * Signature: (II)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_sndrcvinfo;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1DEFAULT_1SEND_1PARAM
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_DEFAULT_SEND_PARAM
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_sndrcvinfo;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1DEFAULT_1SEND_1PARAM
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_EVENTS
 * Signature: (I)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_event_subscribe;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1EVENTS
  (JNIEnv *, jobject, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_EVENTS
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_event_subscribe;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1EVENTS
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_I_WANT_MAPPED_V4_ADDR
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1I_1WANT_1MAPPED_1V4_1ADDR
  (JNIEnv *, jobject, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_I_WANT_MAPPED_V4_ADDR
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1I_1WANT_1MAPPED_1V4_1ADDR
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_MAXSEG
 * Signature: (II)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_assoc_value;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1MAXSEG
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_MAXSEG
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_assoc_value;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1MAXSEG
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_STATUS
 * Signature: (II)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_status;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1STATUS
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_PEER_ADDR_INFO
 * Signature: (IILjava/net/InetSocketAddress;)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_paddrinfo;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1PEER_1ADDR_1INFO
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_DELAYED_SACK
 * Signature: (II)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_sack_info;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1DELAYED_1SACK
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_DELAYED_SACK
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_sack_info;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1DELAYED_1SACK
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_CONTEXT
 * Signature: (II)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_assoc_value;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1CONTEXT
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_CONTEXT
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_assoc_value;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1CONTEXT
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_FRAGMENT_INTERLEAVE
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1FRAGMENT_1INTERLEAVE
  (JNIEnv *, jobject, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_FRAGMENT_INTERLEAVE
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1FRAGMENT_1INTERLEAVE
  (JNIEnv *, jobject, jint, jboolean);
  
/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_REUSE_PORT
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1REUSE_1ADDR
  (JNIEnv *, jobject, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_REUSE_PORT
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1REUSE_1ADDR
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_PARTIAL_DELIVERY_POINT
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1PARTIAL_1DELIVERY_1POINT
  (JNIEnv *, jobject, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_PARTIAL_DELIVERY_POINT
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1PARTIAL_1DELIVERY_1POINT
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_MAX_BURST
 * Signature: (II)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_assoc_value;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1MAX_1BURST
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_MAX_BURST
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_assoc_value;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1MAX_1BURST
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_AUTH_CHUNK
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_authchunk;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1AUTH_1CHUNK
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_HMAC_IDENT
 * Signature: (I)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_hmacalgo;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1HMAC_1IDENT
  (JNIEnv *, jobject, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_HMAC_IDENT
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_hmacalgo;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1HMAC_1IDENT
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_AUTH_KEY
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_authkey;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1AUTH_1KEY
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_AUTH_ACTIVE_KEY
 * Signature: (II)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_authkeyid;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1AUTH_1ACTIVE_1KEY
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_AUTH_ACTIVE_KEY
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_authkeyid;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1AUTH_1ACTIVE_1KEY
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_setSCTP_AUTH_DELETE_KEY
 * Signature: (ILalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_authkeyid;)V
 */
JNIEXPORT void JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1setSCTP_1AUTH_1DELETE_1KEY
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_PEER_AUTH_CHUNKS
 * Signature: (II)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_authchunks;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1PEER_1AUTH_1CHUNKS
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper
 * Method:    n_getSCTP_LOCAL_AUTH_CHUNKS
 * Signature: (II)Lalcatel/tess/hometop/gateways/reactor/sctp/structs/sctp_authchunks;
 */
JNIEXPORT jobject JNICALL Java_alcatel_tess_hometop_gateways_reactor_impl_SctpSocketOptionHelper_n_1getSCTP_1LOCAL_1AUTH_1CHUNKS
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
