---
- hosts: asr.admin
  user: nxuser
  tags: blueprint
  tasks:
    - name: Create application descriptor directory
      file: path=/opt/proxy/install/blueprint/application/blueprints state=directory

    - name: Copy application descriptor
      copy: src=DiameterLB.DiamLB.CalloutAgent dest=/opt/proxy/install/blueprint/application/blueprints/DiameterLB.DiamLB.CalloutAgent backup=yes

- hosts: asr.io
  user: nxuser
  tags: instance
  tasks:
    - name: Declare instance
      copy: src=diamlb.group dest=/tmp/diamlb.group

    - name: Deploy instance
      script: /opt/proxy/localinstances/asr/monitors/monitor/scripts/autoDeployApplication.sh /tmp/diamlb.group creates=/opt/proxy/localinstances/DiameterLB/DiamLB/CalloutAgent/.instances

- hosts: asr.admin
  user: nxuser
  tags: configure
  tasks:
    - name: Disable HA session
      script: /opt/proxy/localinstances/asr/monitors/monitor/scripts/updateProperty.sh -name DiameterLB/DiamLB/CalloutAgent/agent/agent.ha -value false

    - name: Copy default tcpserver.xml
      copy: src=tcpserver.xml dest=/tmp/tcpserver.xml 

    - name: Configure TCP server with Diameter VIP
      script: /opt/proxy/localinstances/asr/monitors/monitor/scripts/updateProperty.sh -name DiameterLB/DiamLB/CalloutAgent/com.alcatel.as.ioh.impl.server.ServerFactoryImpl/conf.tcp.servers -file /tmp/tcpserver.xml
      

    